version: '3.1'

services:
  springboot:
    image: 351540836833.dkr.ecr.eu-north-1.amazonaws.com/my-repo:VERSION
    environment:
    - MONGO_DB_HOSTNAME=mongo
    - MONGO_DB_USERNAME=mongodb
    - MONGO_DB_PASSWORD=mongo@123
    ports:
      - 8081:8080
    working_dir: /opt/app
    depends_on:
      - mongo
    networks:
    - demonetwork  

  mongo:
    image: mongo
    environment:
    - MONGO_INITDB_ROOT_USERNAME=mongodb
    - MONGO_INITDB_ROOT_PASSWORD=mongo@123
    volumes:
      - mongodbvolume:/data/db
   # restart: always
    networks:
    - demonetwork
    
